/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.11 Sat Apr 25 12:07:25 2026.
 */

#include <string.h>

#include "rivanna3_s.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int rivanna3_s_aux_battery_status_pack(
    uint8_t *dst_p,
    const struct rivanna3_s_aux_battery_status_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u16(src_p->aux_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->aux_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->percent_full, 0u, 0xffu);

    return (3);
}

int rivanna3_s_aux_battery_status_unpack(
    struct rivanna3_s_aux_battery_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->aux_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->aux_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->percent_full = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int rivanna3_s_aux_battery_status_init(struct rivanna3_s_aux_battery_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rivanna3_s_aux_battery_status_t));

    return 0;
}

uint16_t rivanna3_s_aux_battery_status_aux_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double rivanna3_s_aux_battery_status_aux_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool rivanna3_s_aux_battery_status_aux_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t rivanna3_s_aux_battery_status_percent_full_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_aux_battery_status_percent_full_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_aux_battery_status_percent_full_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int rivanna3_s_motor_commands_pack(
    uint8_t *dst_p,
    const struct rivanna3_s_motor_commands_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->regen_braking, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->regen_braking, 8u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->cruise_speed, 1u, 0xfeu);
    dst_p[2] |= pack_left_shift_u16(src_p->throttle, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->throttle, 8u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->manual_drive, 1u, 0x02u);
    dst_p[3] |= pack_left_shift_u8(src_p->regen_drive, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->cruise_drive, 3u, 0x08u);

    return (4);
}

int rivanna3_s_motor_commands_unpack(
    struct rivanna3_s_motor_commands_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->regen_braking = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->regen_braking |= unpack_left_shift_u16(src_p[1], 8u, 0x01u);
    dst_p->cruise_speed = unpack_right_shift_u8(src_p[1], 1u, 0xfeu);
    dst_p->throttle = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->throttle |= unpack_left_shift_u16(src_p[3], 8u, 0x01u);
    dst_p->manual_drive = unpack_right_shift_u8(src_p[3], 1u, 0x02u);
    dst_p->regen_drive = unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->cruise_drive = unpack_right_shift_u8(src_p[3], 3u, 0x08u);

    return (0);
}

int rivanna3_s_motor_commands_init(struct rivanna3_s_motor_commands_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rivanna3_s_motor_commands_t));

    return 0;
}

uint16_t rivanna3_s_motor_commands_regen_braking_encode(double value)
{
    return (uint16_t)(value);
}

double rivanna3_s_motor_commands_regen_braking_decode(uint16_t value)
{
    return ((double)value);
}

bool rivanna3_s_motor_commands_regen_braking_is_in_range(uint16_t value)
{
    return (value <= 256u);
}

uint8_t rivanna3_s_motor_commands_cruise_speed_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_motor_commands_cruise_speed_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_motor_commands_cruise_speed_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

uint16_t rivanna3_s_motor_commands_throttle_encode(double value)
{
    return (uint16_t)(value);
}

double rivanna3_s_motor_commands_throttle_decode(uint16_t value)
{
    return ((double)value);
}

bool rivanna3_s_motor_commands_throttle_is_in_range(uint16_t value)
{
    return (value <= 256u);
}

uint8_t rivanna3_s_motor_commands_manual_drive_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_motor_commands_manual_drive_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_motor_commands_manual_drive_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rivanna3_s_motor_commands_regen_drive_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_motor_commands_regen_drive_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_motor_commands_regen_drive_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rivanna3_s_motor_commands_cruise_drive_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_motor_commands_cruise_drive_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_motor_commands_cruise_drive_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int rivanna3_s_dashboard_commands_pack(
    uint8_t *dst_p,
    const struct rivanna3_s_dashboard_commands_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->hazards, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->left_turn_signal, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->right_turn_signal, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->regen_en, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->cruise_inc, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->cruise_en, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->cruise_dec, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->charging_mode_en, 7u, 0x80u);

    return (1);
}

int rivanna3_s_dashboard_commands_unpack(
    struct rivanna3_s_dashboard_commands_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->hazards = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->left_turn_signal = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->right_turn_signal = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->regen_en = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->cruise_inc = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->cruise_en = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->cruise_dec = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->charging_mode_en = unpack_right_shift_u8(src_p[0], 7u, 0x80u);

    return (0);
}

int rivanna3_s_dashboard_commands_init(struct rivanna3_s_dashboard_commands_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rivanna3_s_dashboard_commands_t));

    return 0;
}

uint8_t rivanna3_s_dashboard_commands_hazards_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_dashboard_commands_hazards_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_dashboard_commands_hazards_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rivanna3_s_dashboard_commands_left_turn_signal_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_dashboard_commands_left_turn_signal_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_dashboard_commands_left_turn_signal_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rivanna3_s_dashboard_commands_right_turn_signal_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_dashboard_commands_right_turn_signal_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_dashboard_commands_right_turn_signal_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rivanna3_s_dashboard_commands_regen_en_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_dashboard_commands_regen_en_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_dashboard_commands_regen_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rivanna3_s_dashboard_commands_cruise_inc_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_dashboard_commands_cruise_inc_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_dashboard_commands_cruise_inc_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rivanna3_s_dashboard_commands_cruise_en_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_dashboard_commands_cruise_en_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_dashboard_commands_cruise_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rivanna3_s_dashboard_commands_cruise_dec_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_dashboard_commands_cruise_dec_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_dashboard_commands_cruise_dec_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rivanna3_s_dashboard_commands_charging_mode_en_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_dashboard_commands_charging_mode_en_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_dashboard_commands_charging_mode_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int rivanna3_s_heartbeat_pack(
    uint8_t *dst_p,
    const struct rivanna3_s_heartbeat_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->source, 0u, 0xffu);

    return (1);
}

int rivanna3_s_heartbeat_unpack(
    struct rivanna3_s_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->source = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int rivanna3_s_heartbeat_init(struct rivanna3_s_heartbeat_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rivanna3_s_heartbeat_t));

    return 0;
}

uint8_t rivanna3_s_heartbeat_source_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_heartbeat_source_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_heartbeat_source_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int rivanna3_s_pedal_status_pack(
    uint8_t *dst_p,
    const struct rivanna3_s_pedal_status_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u16(src_p->throttle_pedal, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->throttle_pedal, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u16(src_p->brake_pedal, 4u, 0xf0u);
    dst_p[2] |= pack_right_shift_u16(src_p->brake_pedal, 4u, 0xffu);

    return (3);
}

int rivanna3_s_pedal_status_unpack(
    struct rivanna3_s_pedal_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->throttle_pedal = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->throttle_pedal |= unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->brake_pedal = unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->brake_pedal |= unpack_left_shift_u16(src_p[2], 4u, 0xffu);

    return (0);
}

int rivanna3_s_pedal_status_init(struct rivanna3_s_pedal_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rivanna3_s_pedal_status_t));

    return 0;
}

uint16_t rivanna3_s_pedal_status_throttle_pedal_encode(double value)
{
    return (uint16_t)(value);
}

double rivanna3_s_pedal_status_throttle_pedal_decode(uint16_t value)
{
    return ((double)value);
}

bool rivanna3_s_pedal_status_throttle_pedal_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t rivanna3_s_pedal_status_brake_pedal_encode(double value)
{
    return (uint16_t)(value);
}

double rivanna3_s_pedal_status_brake_pedal_decode(uint16_t value)
{
    return ((double)value);
}

bool rivanna3_s_pedal_status_brake_pedal_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int rivanna3_s_precharge_status_pack(
    uint8_t *dst_p,
    const struct rivanna3_s_precharge_status_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->motor_stage, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u8(src_p->mppt_stage, 3u, 0x38u);
    dst_p[0] |= pack_left_shift_u8(src_p->cont12_fault, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->other_fault, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u16(src_p->threshold, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->threshold, 8u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->cont12, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(src_p->cont12, 4u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->hal_effect_motor, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->hal_effect_motor, 8u, 0x0fu);
    dst_p[5] |= pack_left_shift_u16(src_p->hal_effect_mppt, 4u, 0xf0u);
    dst_p[6] |= pack_right_shift_u16(src_p->hal_effect_mppt, 4u, 0xffu);

    return (7);
}

int rivanna3_s_precharge_status_unpack(
    struct rivanna3_s_precharge_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->motor_stage = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->mppt_stage = unpack_right_shift_u8(src_p[0], 3u, 0x38u);
    dst_p->cont12_fault = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->other_fault = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->threshold = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->threshold |= unpack_left_shift_u16(src_p[2], 8u, 0x0fu);
    dst_p->cont12 = unpack_right_shift_u16(src_p[2], 4u, 0xf0u);
    dst_p->cont12 |= unpack_left_shift_u16(src_p[3], 4u, 0xffu);
    dst_p->hal_effect_motor = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->hal_effect_motor |= unpack_left_shift_u16(src_p[5], 8u, 0x0fu);
    dst_p->hal_effect_mppt = unpack_right_shift_u16(src_p[5], 4u, 0xf0u);
    dst_p->hal_effect_mppt |= unpack_left_shift_u16(src_p[6], 4u, 0xffu);

    return (0);
}

int rivanna3_s_precharge_status_init(struct rivanna3_s_precharge_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rivanna3_s_precharge_status_t));

    return 0;
}

uint8_t rivanna3_s_precharge_status_motor_stage_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_precharge_status_motor_stage_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_precharge_status_motor_stage_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t rivanna3_s_precharge_status_mppt_stage_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_precharge_status_mppt_stage_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_precharge_status_mppt_stage_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t rivanna3_s_precharge_status_cont12_fault_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_precharge_status_cont12_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_precharge_status_cont12_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rivanna3_s_precharge_status_other_fault_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_precharge_status_other_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_precharge_status_other_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t rivanna3_s_precharge_status_threshold_encode(double value)
{
    return (uint16_t)(value);
}

double rivanna3_s_precharge_status_threshold_decode(uint16_t value)
{
    return ((double)value);
}

bool rivanna3_s_precharge_status_threshold_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t rivanna3_s_precharge_status_cont12_encode(double value)
{
    return (uint16_t)(value);
}

double rivanna3_s_precharge_status_cont12_decode(uint16_t value)
{
    return ((double)value);
}

bool rivanna3_s_precharge_status_cont12_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t rivanna3_s_precharge_status_hal_effect_motor_encode(double value)
{
    return (uint16_t)(value);
}

double rivanna3_s_precharge_status_hal_effect_motor_decode(uint16_t value)
{
    return ((double)value);
}

bool rivanna3_s_precharge_status_hal_effect_motor_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t rivanna3_s_precharge_status_hal_effect_mppt_encode(double value)
{
    return (uint16_t)(value);
}

double rivanna3_s_precharge_status_hal_effect_mppt_decode(uint16_t value)
{
    return ((double)value);
}

bool rivanna3_s_precharge_status_hal_effect_mppt_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int rivanna3_s_contactor12_error_pack(
    uint8_t *dst_p,
    const struct rivanna3_s_contactor12_error_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->cont12_went_low, 0u, 0x01u);

    return (1);
}

int rivanna3_s_contactor12_error_unpack(
    struct rivanna3_s_contactor12_error_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->cont12_went_low = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int rivanna3_s_contactor12_error_init(struct rivanna3_s_contactor12_error_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rivanna3_s_contactor12_error_t));

    return 0;
}

uint8_t rivanna3_s_contactor12_error_cont12_went_low_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_contactor12_error_cont12_went_low_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_contactor12_error_cont12_went_low_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int rivanna3_s_update_control_pack(
    uint8_t *dst_p,
    const struct rivanna3_s_update_control_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->target_board, 0u, 0x0fu);
    dst_p[0] |= pack_left_shift_u8(src_p->setup, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->setup_ack, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->ready_for_data, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->done, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u32(src_p->final_crc, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->final_crc, 8u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->final_crc, 16u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->final_crc, 24u, 0xffu);

    return (5);
}

int rivanna3_s_update_control_unpack(
    struct rivanna3_s_update_control_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->target_board = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->setup = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->setup_ack = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->ready_for_data = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->done = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->final_crc = unpack_right_shift_u32(src_p[1], 0u, 0xffu);
    dst_p->final_crc |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    dst_p->final_crc |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
    dst_p->final_crc |= unpack_left_shift_u32(src_p[4], 24u, 0xffu);

    return (0);
}

int rivanna3_s_update_control_init(struct rivanna3_s_update_control_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rivanna3_s_update_control_t));

    return 0;
}

uint8_t rivanna3_s_update_control_target_board_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_update_control_target_board_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_update_control_target_board_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t rivanna3_s_update_control_setup_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_update_control_setup_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_update_control_setup_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rivanna3_s_update_control_setup_ack_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_update_control_setup_ack_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_update_control_setup_ack_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rivanna3_s_update_control_ready_for_data_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_update_control_ready_for_data_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_update_control_ready_for_data_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rivanna3_s_update_control_done_encode(double value)
{
    return (uint8_t)(value);
}

double rivanna3_s_update_control_done_decode(uint8_t value)
{
    return ((double)value);
}

bool rivanna3_s_update_control_done_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint32_t rivanna3_s_update_control_final_crc_encode(double value)
{
    return (uint32_t)(value);
}

double rivanna3_s_update_control_final_crc_decode(uint32_t value)
{
    return ((double)value);
}

bool rivanna3_s_update_control_final_crc_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int rivanna3_s_update_data_pack(
    uint8_t *dst_p,
    const struct rivanna3_s_update_data_t *src_p,
    size_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    dst_p[0] |= pack_left_shift_u64(src_p->data, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->data, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->data, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->data, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->data, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->data, 40u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->data, 48u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->data, 56u, 0xffu);
    dst_p[8] |= pack_right_shift_u64(src_p->data, 64u, 0xffu);
    dst_p[9] |= pack_right_shift_u64(src_p->data, 72u, 0xffu);
    dst_p[10] |= pack_right_shift_u64(src_p->data, 80u, 0xffu);
    dst_p[11] |= pack_right_shift_u64(src_p->data, 88u, 0xffu);
    dst_p[12] |= pack_right_shift_u64(src_p->data, 96u, 0xffu);
    dst_p[13] |= pack_right_shift_u64(src_p->data, 104u, 0xffu);
    dst_p[14] |= pack_right_shift_u64(src_p->data, 112u, 0xffu);
    dst_p[15] |= pack_right_shift_u64(src_p->data, 120u, 0xffu);
    dst_p[16] |= pack_right_shift_u64(src_p->data, 128u, 0xffu);
    dst_p[17] |= pack_right_shift_u64(src_p->data, 136u, 0xffu);
    dst_p[18] |= pack_right_shift_u64(src_p->data, 144u, 0xffu);
    dst_p[19] |= pack_right_shift_u64(src_p->data, 152u, 0xffu);
    dst_p[20] |= pack_right_shift_u64(src_p->data, 160u, 0xffu);
    dst_p[21] |= pack_right_shift_u64(src_p->data, 168u, 0xffu);
    dst_p[22] |= pack_right_shift_u64(src_p->data, 176u, 0xffu);
    dst_p[23] |= pack_right_shift_u64(src_p->data, 184u, 0xffu);
    dst_p[24] |= pack_right_shift_u64(src_p->data, 192u, 0xffu);
    dst_p[25] |= pack_right_shift_u64(src_p->data, 200u, 0xffu);
    dst_p[26] |= pack_right_shift_u64(src_p->data, 208u, 0xffu);
    dst_p[27] |= pack_right_shift_u64(src_p->data, 216u, 0xffu);
    dst_p[28] |= pack_right_shift_u64(src_p->data, 224u, 0xffu);
    dst_p[29] |= pack_right_shift_u64(src_p->data, 232u, 0xffu);
    dst_p[30] |= pack_right_shift_u64(src_p->data, 240u, 0xffu);
    dst_p[31] |= pack_right_shift_u64(src_p->data, 248u, 0xffu);
    dst_p[32] |= pack_right_shift_u64(src_p->data, 256u, 0xffu);
    dst_p[33] |= pack_right_shift_u64(src_p->data, 264u, 0xffu);
    dst_p[34] |= pack_right_shift_u64(src_p->data, 272u, 0xffu);
    dst_p[35] |= pack_right_shift_u64(src_p->data, 280u, 0xffu);
    dst_p[36] |= pack_right_shift_u64(src_p->data, 288u, 0xffu);
    dst_p[37] |= pack_right_shift_u64(src_p->data, 296u, 0xffu);
    dst_p[38] |= pack_right_shift_u64(src_p->data, 304u, 0xffu);
    dst_p[39] |= pack_right_shift_u64(src_p->data, 312u, 0xffu);
    dst_p[40] |= pack_right_shift_u64(src_p->data, 320u, 0xffu);
    dst_p[41] |= pack_right_shift_u64(src_p->data, 328u, 0xffu);
    dst_p[42] |= pack_right_shift_u64(src_p->data, 336u, 0xffu);
    dst_p[43] |= pack_right_shift_u64(src_p->data, 344u, 0xffu);
    dst_p[44] |= pack_right_shift_u64(src_p->data, 352u, 0xffu);
    dst_p[45] |= pack_right_shift_u64(src_p->data, 360u, 0xffu);
    dst_p[46] |= pack_right_shift_u64(src_p->data, 368u, 0xffu);
    dst_p[47] |= pack_right_shift_u64(src_p->data, 376u, 0xffu);
    dst_p[48] |= pack_right_shift_u64(src_p->data, 384u, 0xffu);
    dst_p[49] |= pack_right_shift_u64(src_p->data, 392u, 0xffu);
    dst_p[50] |= pack_right_shift_u64(src_p->data, 400u, 0xffu);
    dst_p[51] |= pack_right_shift_u64(src_p->data, 408u, 0xffu);
    dst_p[52] |= pack_right_shift_u64(src_p->data, 416u, 0xffu);
    dst_p[53] |= pack_right_shift_u64(src_p->data, 424u, 0xffu);
    dst_p[54] |= pack_right_shift_u64(src_p->data, 432u, 0xffu);
    dst_p[55] |= pack_right_shift_u64(src_p->data, 440u, 0xffu);
    dst_p[56] |= pack_right_shift_u64(src_p->data, 448u, 0xffu);
    dst_p[57] |= pack_right_shift_u64(src_p->data, 456u, 0xffu);
    dst_p[58] |= pack_right_shift_u64(src_p->data, 464u, 0xffu);
    dst_p[59] |= pack_right_shift_u64(src_p->data, 472u, 0xffu);
    dst_p[60] |= pack_right_shift_u64(src_p->data, 480u, 0xffu);
    dst_p[61] |= pack_right_shift_u64(src_p->data, 488u, 0xffu);
    dst_p[62] |= pack_right_shift_u64(src_p->data, 496u, 0xffu);
    dst_p[63] |= pack_right_shift_u64(src_p->data, 504u, 0xffu);

    return (64);
}

int rivanna3_s_update_data_unpack(
    struct rivanna3_s_update_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    dst_p->data = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[6], 48u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[7], 56u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[8], 64u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[9], 72u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[10], 80u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[11], 88u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[12], 96u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[13], 104u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[14], 112u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[15], 120u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[16], 128u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[17], 136u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[18], 144u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[19], 152u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[20], 160u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[21], 168u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[22], 176u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[23], 184u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[24], 192u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[25], 200u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[26], 208u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[27], 216u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[28], 224u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[29], 232u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[30], 240u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[31], 248u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[32], 256u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[33], 264u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[34], 272u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[35], 280u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[36], 288u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[37], 296u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[38], 304u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[39], 312u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[40], 320u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[41], 328u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[42], 336u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[43], 344u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[44], 352u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[45], 360u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[46], 368u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[47], 376u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[48], 384u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[49], 392u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[50], 400u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[51], 408u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[52], 416u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[53], 424u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[54], 432u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[55], 440u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[56], 448u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[57], 456u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[58], 464u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[59], 472u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[60], 480u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[61], 488u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[62], 496u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[63], 504u, 0xffu);

    return (0);
}

int rivanna3_s_update_data_init(struct rivanna3_s_update_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rivanna3_s_update_data_t));

    return 0;
}

uint64_t rivanna3_s_update_data_data_encode(double value)
{
    return (uint64_t)(value);
}

double rivanna3_s_update_data_data_decode(uint64_t value)
{
    return ((double)value);
}

bool rivanna3_s_update_data_data_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int rivanna3_s_odometry_data_pack(
    uint8_t *dst_p,
    const struct rivanna3_s_odometry_data_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u32(src_p->distance, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->distance, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->distance, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->distance, 24u, 0xffu);

    return (4);
}

int rivanna3_s_odometry_data_unpack(
    struct rivanna3_s_odometry_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->distance = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->distance |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->distance |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->distance |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

int rivanna3_s_odometry_data_init(struct rivanna3_s_odometry_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rivanna3_s_odometry_data_t));

    return 0;
}

uint32_t rivanna3_s_odometry_data_distance_encode(double value)
{
    return (uint32_t)(value);
}

double rivanna3_s_odometry_data_distance_decode(uint32_t value)
{
    return ((double)value);
}

bool rivanna3_s_odometry_data_distance_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}
