/**
 * @file I2C.h
 * @brief C++ wrapper class for I2C communication using STM32 HAL drivers.
 *
 * This class provides an object-oriented interface for configuring and
 * communicating over I2C peripherals on STM32 microcontrollers.
 *
 * It automatically configures GPIO pins, initializes the appropriate
 * I2C peripheral, and provides simplified read/write helper functions.
 *
 * Example usage:
 * @code
 * #include "I2C.h"
 *
 * I2C bus(PB_8, PB_9, 400000);   // I2C1 (SCL=PB8, SDA=PB9), 400 kHz
 *
 * uint8_t data = 0x55;
 * bus.write(0x50, &data, 1);     // Write 1 byte to slave address 0x50
 *
 * uint8_t buffer[4];
 * bus.read(0x50, buffer, 4);     // Read 4 bytes from slave address 0x50
 * @endcode
 *
 * @see stm32h7xx_hal_i2c.h
 * @see pinmap.h
 * @see peripheralmap.h
 */

#ifndef I2C_H
#define I2C_H

#include "stm32h7xx_hal.h"
#include "pinmap.h"
#include "peripheralmap.h"

/**
 * @class I2C
 * @brief Provides I2C communication interface using STM32 HAL.
 */
class I2C {
public:
    /**
     * @brief Indicates whether the I2C peripheral was successfully initialized.
     */
    bool initialized = false;

    /**
     * @brief Constructs an I2C object and initializes the I2C peripheral.
     * @param scl  SCL pin (must correspond to valid I2C SCL mapping).
     * @param sda  SDA pin (must correspond to valid I2C SDA mapping).
     * @param frequency I2C bus frequency (e.g., 100000, 400000, 1000000).
     */
    explicit I2C(Pin scl, Pin sda, uint32_t baudrate);

    /**
     * @brief Writes data to an I2C device (blocking).
     * @param address 7-bit peripheral address (0x00 – 0x7F).
     * @param buffer Pointer to data to transmit.
     * @param length Number of bytes to send.
     */
    void write(uint16_t address, uint8_t *buffer, uint16_t length);

    /**
     * @brief Reads data from an I2C device (blocking).
     * @param address 7-bit peripheral address.
     * @param buffer Buffer where received data is stored.
     * @param length Number of bytes to read.
     */
    void read(uint16_t address, uint8_t *buffer, uint16_t length);


private:
    I2C_HandleTypeDef hi2c;          /**< HAL I2C handle. */

    /**
     * @brief Matching peripheral entry from your peripheral map.
     */
    I2C_Peripheral *i2c_periph;

    /**
     * @brief Initializes GPIO pins for I2C alternate function mode.
     */
    void init_gpio(I2C_Peripheral *i2c_periph);

    /**
     * @brief Initializes the I2C peripheral.
     */
    void init_i2c(uint32_t baudrate);

    /**
     * @brief Finds the I2C peripheral that matches SCL/SDA pin pair.
     * @param scl SCL pin.
     * @param sda SDA pin.
     * @return Pointer to I2C_Peripheral entry, or nullptr if invalid.
     */
    I2C_Peripheral* find_i2c_pins(Pin scl, Pin sda);

    /**
     * @brief Computes the TIMINGR value used to configure the I2C peripheral speed.
     *
     * This function returns a precomputed STM32H743 TIMINGR register value
     * corresponding to the requested I2C bus frequency. The timing values are
     * based on the official STM32 timing formulas and match those generated by
     * STM32CubeMX for:
     *   - I2C kernel clock = 64 MHz (D2PCLK1)
     *   - Analog filter enabled
     *   - Digital filter disabled
     *   - Standard rise/fall times for each mode
     *
     * Supported speeds:
     *   - ≤ 100 kHz  → Standard Mode
     *   - ≤ 400 kHz  → Fast Mode
     *   - ≤ 1 MHz    → Fast Mode Plus
     *
     * @note If an unsupported frequency is requested, the function falls back
     *       to 100 kHz Standard Mode timing (0x10805D89).
     *
     * @param freq_hz Desired I2C bus frequency in Hertz.
     * @return 32-bit TIMINGR value to be assigned to hi2c.Init.Timing.
     */
    uint32_t compute_timing(uint32_t freq_hz);

    Pin scl;                     /**< SCL pin object. */
    Pin sda;                     /**< SDA pin object. */
    uint32_t baudrate;          /**< I2C bus frequency. */
};

#endif // I2C_H
